docker:
  registry:
    server: "https://417782006694.dkr.ecr.us-east-1.amazonaws.com"
    username: "AWS"
    password: "QVdTOmV5SndZWGxzYjJGa0lqb2lSbEJzYWtjMlpsQXZabk5zVG1aVWNqRmhNREpKVjJ4a2QzZE5OSGw2VDNoQ2FYWm9LMlYwUm5NM01IbDFTVlpUYWpGMU9ISlVSVTVYV0U1cWFrSldUbUo0WTNsTWFEQkZXVVZNYmtaMlpqUlVSVlFyYzBJeWVtSlNWbTUyTjNWeWJEUjNjMkpuVDJrd2RXeENZekZoVm14c1EwOXZSa0kyTkhGSlNTODNUVFVyTWpNMlFrNWFSM1l5VEZKYVFrZzRhWE5CZURNM2NGTXpTeXRsVFc5UVdVOXVXV3RrVW5oVVZrMURTREZzY2tKak1GRklSa0p2ZGxWSWNuUlBXSEpTVjBoWFJISlVVakJJVFd4c2REY3hUMnMxY1Zac1lVMWpZVEJJTDFobE4zWlNWVWszUVhwaWEyNHJOMWhTY1daR1YweFpPWGwxZDBFNFkyMU5iMDVNVm1Gbk5uRnpORGwzZEV4bFoxaEpjRk15VFZwTk1EbHdLekZPTlRGWFkxbHpMM2QzY0daUWVFMWFlbmsxVVZKVGRUaHdjVzU0VVhSdE4ycENjbU5RSzJKaFIweE5PVFpKWkZSbmJqWjRaM1pOU0haM2NHMUdibHBhU25Obk9FaEJkamwyTkVGb05XMDBPREprZERSclZIRXJURTloY1hWTE1XRjJLekIyWm5CWWEwMUhia2MwU25aTEx6aDRORFoyYm5Sa2JFTkVUUzgzVTBkbldUYzVTWE5rYUhkcGRra3JjR1ExTXpkcmNVZG9UekZRY2pGMFdIQnNPVkV4WjFKMllYQjVSRkpTTVRWQ1JqWjVOMnQyYjNwdlZrOWxObFpRY0hveVdtbDZWRUo2V2pKbFQwMHhTR1oxTkRZeVYyaGtiM0ZJTkVjME1VNTVlV2xCTUVoRVRVdFZTSHB5TUVGaVpsYzJaalV5TUVKU1ltaHZXbFpDUjB0amRVRXZWa2RNYmsxU1dIbEdlR2xZUkVnNWExaEdkR3BSY2xWcFNTdEhWV1JqZW5GRk1VTXhOalZoYjFSclpIUnpOa1ZNYTBKTWNVczNSR1ZvVHpWT1NGbEtWMGxRUmpSMmJHdFlVV0ZDWXpscFpXWk9TbWRFT0d0Q2JYWTJXREJLT0VWMFJVeG1ObUZhV0RKeFdTdFVVRmtyTlVKMGVHWk1URU5VTW1OVmIxSXhTR0ZRZEdWSFRuUjJXalIyYUhKb05rVnNUMWxrYVZOeU9ERndiazAzVFhWYVRtd3pPRkIyZWxRdlFuSjBMMVZtVWpGSFQzWTJlREF6V0RZNFVrTjVNVGR1UkZoSFZrTlNUWEI0YW10SVJIWklRMlZ2U21saFRFTlVZM1J2ZVZOeWVETnplbVpuWTJKRFQyTlFWbUZtV2xOSGF6RlBVVXBtUVVWaUsyaDVMMGRLT0hReFlXaGpWMHhMZG00eWNXSmlVVGhuVDAxT01VRm9hMDVGTlZWV2EyWk1jVXBXTjFSMVpHWnJWM2x0U21aRllsQnRiMk5UTDB0Q1MzaExUVzlTYXpkbVVUZHVURTFuUm1SbkszTmlMMWczZFcxb1VUVkNiSGR3WTNwSmQwUXZRbUpFWVc1UWRrSnpSM05hWVRGQk16ZHNUamxwWkM4elN5OTNRV2xPY1c5U1VXZDRXRlp6VnpKT1dsQjVlamhuVFdnd05URTVVSFp1VUV4VVNuQXdNa2xOV0VOWk1ITm9lRko1VEVKRk9IcEdURE5qYXpORFdrMHZRM0J5VDJVMmVHNWtUV2xPUWxoa04yaFBRa2hpYTJ3NE4ydEZlSFZVZEcxd1VqbFBZWFJIWWpjd1VFUlpRVWMyTVhsS0swMXlWa3B1SzJGWGEwbENSekZ2WkRGdFVYWnNjVU5XZGtSQ2RGRmphekY2ZVV0RE5HNDVVWGRpU1hBelptMXpjVXRvUWxoWEszVnhUVmwwVUV0TWJuRnZkeXRXY0VWNU4zRkVjbGRKY21oaloyMXNNRGhtY0RWTlEydE1WVGRqV21KUE9GZGxaMkpRU3preFUyOXFRVVppWmsxVE9VcHhZV1ZwWTA1bVRGRnlRVzFxSWl3aVpHRjBZV3RsZVNJNklrRlJSVUpCU0doM2JUQlpZVWxUU21WU2RFcHROVzR4UnpaMWNXVmxhMWgxYjFoWVVHVTFWVVpqWlRsU2NUZ3ZNVFIzUVVGQlNEUjNaa0ZaU2t0dldrbG9kbU5PUVZGalIyOUhPSGRpVVVsQ1FVUkNiMEpuYTNGb2EybEhPWGN3UWtKM1JYZElaMWxLV1VsYVNVRlhWVVJDUVVWMVRVSkZSVVJLWjFwcWJUWTJlVWg2VURRMlNEUnNkMGxDUlVsQk4ycEhWMWhoTUhad1VFNWxNR04xTTFoblZqRk5UVUl4UkRWYVZXTkhjbFpaTkVGYVlYTlphbGxOUWtaR2FYZFVaMVZCTUcxdk1tbFNkRmd6WmpkMFJubDJjbEkzT1dJeVNVeFNXVXR0TDAwOUlpd2lkbVZ5YzJsdmJpSTZJaklpTENKMGVYQmxJam9pUkVGVVFWOUxSVmtpTENKbGVIQnBjbUYwYVc5dUlqb3hOakE1TkRZek1UWXhmUT09"

k8s:
  domain: cluster.local

actormatrix:
  replicaCount: 5
  # can be public|corp
#  ingress: "public"
  namespace: default
#  namespace: "nms"
  httpPort: 8080
  managementPort: 8558
  akkaPort: 2551
  kamonPort: 9225
  kamonStatusPagePort: 5266
  kamonApiKey: ""
  enablePredictions: "off"
  mockBackends: "off"
  mockBackendsNumber: 100
  cpu: 1
  image:
    repository: 417782006694.dkr.ecr.us-east-1.amazonaws.com/actormatrix
    tag: 0.0.20
    pullPolicy: "IfNotPresent"

cluster:
  type: "aws"
#  type: "local"
  primaryDomain: ""
  region: ""
  subDomain: ""
